apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ensemble
  namespace: titangrm-iot
spec:
  ports:
  - port: 2888
    name: follower
  - port: 3888
    name: election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
  namespace: titangrm-iot
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
